# 1일차 Quiz

<div align='right'><b> 류회성(Hoesung Ryu)</b> </div>
<div align='right'> (skainof23@gmail.com) </div>

> 간단하게 Python, NumPy 그리고 Pandas에 대한 간단한 퀴즈를 보겠습니다.

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#-Python-
--" data-toc-modified-id="-Python-
---1"><span class="toc-item-num">1&nbsp;&nbsp;</span><i class="fa fa-tasks"></i> Python 
  </a></span></li><li><span><a href="#-NumPy-
--" data-toc-modified-id="-NumPy-
---2"><span class="toc-item-num">2&nbsp;&nbsp;</span><i class="fa fa-tasks"></i> NumPy 
  </a></span></li><li><span><a href="#-Pandas-
--" data-toc-modified-id="-Pandas-
---3"><span class="toc-item-num">3&nbsp;&nbsp;</span><i class="fa fa-tasks"></i> Pandas 
  </a></span></li><li><span><a href="#Reference" data-toc-modified-id="Reference-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Reference</a></span></li></ul></div>

In [1]:
import os
import sys
import warnings
warnings.filterwarnings(action='ignore')

---
<div class="alert alert-success" data-title="">
  <h2><i class="fa fa-tasks" aria-hidden="true"></i> Python 
  </h2>
</div>

![](https://i.pinimg.com/originals/a6/96/96/a696964ddaf552e14744451d256458d2.jpg)

**Q1.** You are given a list $x=[1,2,3,4,5,6]$. 

Print the third items in list x

In [2]:
x = [1,2,3,4,5,6]

In [3]:
x[2]

3

**Q2.** Print the reversed order of list $x=[1,2,3,4,5,6]$

In [4]:
x[::-1]

[6, 5, 4, 3, 2, 1]

**Q3.** Given a list iterate it and display numbers which are divisible by $5$ 

- List = [12, 15, 32, 42, 55, 75, 122, 132]
   

In [5]:
list_ = [12, 15, 32, 42, 55, 75, 122, 132, 150, 180, 200]
for item in list_:
    if(item % 5 == 0):
        print(item)

15
55
75
150
180
200


**Q4.** Print the following pattern:
```
    1 
    1 2 
    1 2 3 
    1 2 3 4 
    1 2 3 4 5
```

In [6]:
lastNumber = 6
for row in range(1, lastNumber):
    for column in range(1, row + 1):
        print(column, end=' ')
    print("")

1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5 


**Q5.** Print the following pattern:

```
    5 4 3 2 1 
    4 3 2 1 
    3 2 1 
    2 1 
    1
    
    
```

In [7]:
n = 5
k = 5
for i in range(0,n+1):
    for j in range(k-i,0,-1):
        print(j,end=' ')
    print()

5 4 3 2 1 
4 3 2 1 
3 2 1 
2 1 
1 



**Q6.** The Fibonacci sequence is defined as below:
$$F_n = F_{n-1} + F_{n-2}$$

where $n$ denotes the $n^\text{th}$ item of the Fibonacci sequence. You are given the first three numbers of the Fibonacci sequence as F = [0, 1, 1]. Create a for loop to determine the next 20 numbers of the Fibonacci sequence. Print F with the final 23 numbers. 

_Hint: use F.append() to add a new Fibonacci value to the end of the list F._

In [8]:
F = [0, 1, 1]
for n in range(3, 23):
    f_n = F[n - 1] + F[n - 2]
    F.append(f_n)
print(F)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711]


**Q7.** Given the list $x = [2.0,3.0,5.0,7.0,9.0]$, create a list $Y(x)$ for each float in x. Print the list $Y$.
$$Y(x) = \frac{(3.0x)^2}{(99x - x^3)} - \frac{1}{x}$$


In [9]:
# Q7
x = [2.0, 3.0, 5.0, 7.0, 9.0]
Y = []
for v in x:
    new_val = (3.0 * v) ** 2 / (99 * v - v ** 3) - 1 / v
    Y.append(new_val)    

# one-liner with list-comprehension:
Y = [(3.0 * v) ** 2 / (99 * v - v ** 3) - 1 / v
     for v in x]

print(Y)

[-0.31052631578947365, -0.033333333333333326, 0.4081081081081081, 1.1171428571428572, 4.388888888888889]


---

<div class="alert alert-success" data-title="">
  <h2><i class="fa fa-tasks" aria-hidden="true"></i> NumPy 
  </h2>
</div>

![](https://datacamp-community-prod.s3.amazonaws.com/be48d587-e32a-4009-9c29-5b24f4a0edf3)

In [10]:
import numpy as np

**Q1.** Create a null vector of size 10 (★☆☆)

In [11]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


**Q2.** Reverse the below list(first element becomes last) (★☆☆):  

```python
x = [1,2,3,4,5]
```

In [12]:
X = [1,2,3,4,5]

In [13]:
X[::-1]

[5, 4, 3, 2, 1]

**Q3.** Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)
(hint: np.linspace)

In [14]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


**Q4.** Create a random vector of size 10 and sort it (★★☆)

In [15]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.02889321 0.39602243 0.40008064 0.48197894 0.52795913 0.55275259
 0.75936614 0.82002682 0.91805959 0.93233571]


**Q5.** Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [16]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.006461933927761954 0.9744015893640688


**Q6.** Create a 3x3x3 array with random values (★☆☆)

In [17]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.6896078  0.59597608 0.43508025]
  [0.83440615 0.03484723 0.15020937]
  [0.60759487 0.83454451 0.72601657]]

 [[0.64333068 0.62188361 0.5527411 ]
  [0.37278046 0.30690588 0.80008019]
  [0.51429488 0.71915612 0.99470295]]

 [[0.20987646 0.12009793 0.39928661]
  [0.46249193 0.27473153 0.7594266 ]
  [0.16051055 0.95553955 0.72917551]]]


**Q7.** solve the equation $F=M \times a $  for a (hint: np.linalg.solve) 

```python 
M = np.array([[2,3],[-2,9]])
F = np.array([12.9,12.3])
```

In [18]:
M = np.array([[2,3],[-2,9]])
F = np.array([12.9,12.3])

In [19]:
a = np.linalg.solve(M,F)
print(a)

[3.3 2.1]


**Q8.** dot product(matrix multiplication)

prodcut those two values t1, t2 
```python
t1 = np.array([[1,2],[2,3]])
t2 = np.array([[3,5],[4,6]])
```

In [20]:
t1 = np.array([[1,2],[2,3]])
t2 = np.array([[3,5],[4,6]])

In [21]:
t1 @ t2

array([[11, 17],
       [18, 28]])

**Q9.** Consider the following four $x,y$ data points.

|$x$ |$y$| 
|--|--|
|0.0 | 1.1 |
|0.7 | 2.99| 
|1.7 | 5.69| 
|2.1 |6.77 |

where an equation of a line is defined as


$$y = mx + b$$

The matrix equation for fitting a line is defined as
\begin{equation}
\begin{bmatrix}
x_1 & 1.0 \\
x_2 & 1.0 \\
\vdots & \vdots \\
x_n & 1.0 \\
\end{bmatrix}\begin{bmatrix}
m  \\
b
\end{bmatrix}
= \begin{bmatrix}
y_1 \\
y_2 \\
\vdots \\
y_n \\
\end{bmatrix}
\end{equation} 

where the first data points are $x_1$ and $y_1$. The second data points are $x_2$ and $y_2$, and so forth. 


In [22]:
x = np.array([0.0, 0.7, 1.7, 2.1])
y = np.array([1.1, 2.99, 5.69, 6.77])
A = np.vstack([x, np.ones(len(x))]).T
# or
A = np.array([x, np.ones(len(x))]).T
c, residuals, rank, sing = np.linalg.lstsq(A, y)
print(c)
print(residuals)
print(rank)

[2.7 1.1]
[1.42981039e-30]
2


---

<div class="alert alert-success" data-title="">
  <h2><i class="fa fa-tasks" aria-hidden="true"></i> Pandas 
  </h2>
</div>

![](https://media-exp1.licdn.com/dms/image/C5612AQEeBt4lps_6Hg/article-cover_image-shrink_720_1280/0?e=1601510400&v=beta&t=LfVlgjOt7mNBBTZ3W53fyBeQAn533PSVlEamNpiT2Zc)

**Q1.** Import pandas under the alias `pd`.

In [23]:
import pandas as pd

**Q2.** Print the version of pandas that has been imported.

In [24]:
pd.__version__

'1.0.3'

**Q3.** Print out all the version information of the libraries that are required by the pandas library.

In [25]:
pd.show_versions()


INSTALLED VERSIONS
------------------
commit           : None
python           : 3.6.10.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : AMD64 Family 23 Model 1 Stepping 1, AuthenticAMD
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 1.0.3
numpy            : 1.16.6
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 47.1.1.post20200604
Cython           : 0.29.21
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.5.1
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.13.0
pandas_datareader: None
bs4              : 4.6.0
bottleneck       : None
fastparquet      : None
gcsfs            : None
lxml.etree       : 4.5.1
ma

Note: remember to import numpy using:
```python
import numpy as np
```

Consider the following Python dictionary `data` and Python list `labels`:

``` python
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```
(This is just some meaningless data I made up with the theme of animals and trips to a vet.)

**Q4.** Create a DataFrame `df` from this dictionary `data` which has the index `labels`.

In [28]:
import numpy as np

data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data, index=labels)

**Q5.** Display a summary of the basic information about this DataFrame and its data (*hint: there is a single method that can be called on the DataFrame*).

In [29]:
df.info()

# ...or...

df.describe()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   animal    10 non-null     object 
 1   age       8 non-null      float64
 2   visits    10 non-null     int64  
 3   priority  10 non-null     object 
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes


age     visits
count  8.000000  10.000000
mean   3.437500   1.900000
std    2.007797   0.875595
min    0.500000   1.000000
25%    2.375000   1.000000
50%    3.000000   2.000000
75%    4.625000   2.750000
max    7.000000   3.000000

**Q6.** Return the first 3 rows of the DataFrame `df`.

In [30]:
df.iloc[:3]

# or equivalently

df.head(3)

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no

**Q7.** Select just the 'animal' and 'age' columns from the DataFrame `df`.

In [31]:
df.loc[:, ['animal', 'age']]

# or

df[['animal', 'age']]

animal  age
a    cat  2.5
b    cat  3.0
c  snake  0.5
d    dog  NaN
e    dog  5.0
f    cat  2.0
g  snake  4.5
h    cat  NaN
i    dog  7.0
j    dog  3.0

**Q8.** Select the data in rows `[3, 4, 8]` *and* in columns `['animal', 'age']`.

In [32]:
df.loc[df.index[[3, 4, 8]], ['animal', 'age']]

animal  age
d    dog  NaN
e    dog  5.0
i    dog  7.0

**Q9.** Select only the rows where the number of visits is greater than 3.

In [33]:
df[df['visits'] > 3]

Empty DataFrame
Columns: [animal, age, visits, priority]
Index: []

**Q10.** Select the rows where the age is missing, i.e. it is `NaN`.

In [34]:
df[df['age'].isnull()]

animal  age  visits priority
d    dog  NaN       3      yes
h    cat  NaN       1      yes

**Q11.** Select the rows where the animal is a cat *and* the age is less than 3.

In [35]:
df[(df['animal'] == 'cat') & (df['age'] < 3)]

animal  age  visits priority
a    cat  2.5       1      yes
f    cat  2.0       3       no

**Q12.** Select the rows the age is between 2 and 4 (inclusive).

In [36]:
df[df['age'].between(2, 4)]

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
f    cat  2.0       3       no
j    dog  3.0       1       no

**Q13.** Change the age in row 'f' to 1.5.

In [37]:
df.loc['f', 'age'] = 1.5
df

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

**Q14.** Calculate the sum of all visits in `df` (i.e. the total number of visits).

In [38]:
df['visits'].sum()

19

**Q15.** Calculate the mean age for each different animal in `df`.

In [39]:
df.groupby('animal')['age'].mean()

animal
cat      2.333333
dog      5.000000
snake    2.500000
Name: age, dtype: float64

**Q16.** Append a new row 'k' to `df` with your choice of values for each column. Then delete that row to return the original DataFrame.

In [40]:
df.loc['k'] = [5.5, 'dog', 'no', 2]

# and then deleting the new row...

df = df.drop('k')
df

animal  age visits priority
a    cat  2.5      1      yes
b    cat    3      3      yes
c  snake  0.5      2       no
d    dog  NaN      3      yes
e    dog    5      2       no
f    cat  1.5      3       no
g  snake  4.5      1       no
h    cat  NaN      1      yes
i    dog    7      2       no
j    dog    3      1       no

**Q17.** Count the number of each type of animal in `df`.

In [41]:
df['animal'].value_counts()

dog      4
cat      4
snake    2
Name: animal, dtype: int64

**Q18.** Sort `df` first by the values in the 'age' in *decending* order, then by the value in the 'visit' column in *ascending* order (so row `i` should be first, and row `d` should be last).

In [42]:
df.sort_values(by=['age', 'visits'], ascending=[False, True])

animal  age visits priority
i    dog    7      2       no
e    dog    5      2       no
g  snake  4.5      1       no
j    dog    3      1       no
b    cat    3      3      yes
a    cat  2.5      1      yes
f    cat  1.5      3       no
c  snake  0.5      2       no
h    cat  NaN      1      yes
d    dog  NaN      3      yes

**Q19.** The 'priority' column contains the values 'yes' and 'no'. Replace this column with a column of boolean values: 'yes' should be `True` and 'no' should be `False`.

In [43]:
df['priority'] = df['priority'].map({'yes': True, 'no': False})
df

animal  age visits  priority
a    cat  2.5      1      True
b    cat    3      3      True
c  snake  0.5      2     False
d    dog  NaN      3      True
e    dog    5      2     False
f    cat  1.5      3     False
g  snake  4.5      1     False
h    cat  NaN      1      True
i    dog    7      2     False
j    dog    3      1     False

**Q20.** In the 'animal' column, change the 'snake' entries to 'python'.

In [44]:
df['animal'] = df['animal'].replace('snake', 'python')

In [45]:
df

animal  age visits  priority
a     cat  2.5      1      True
b     cat    3      3      True
c  python  0.5      2     False
d     dog  NaN      3      True
e     dog    5      2     False
f     cat  1.5      3     False
g  python  4.5      1     False
h     cat  NaN      1      True
i     dog    7      2     False
j     dog    3      1     False

## Reference

- https://rfriend.tistory.com/346