# 1일차 Quiz

<div align='right'><b> 류회성(Hoesung Ryu)</b> </div>
<div align='right'> (skainof23@gmail.com) </div>

> 간단하게 Python, NumPy 그리고 Pandas에 대한 간단한 퀴즈를 보겠습니다.

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#-Python-
--" data-toc-modified-id="-Python-
---1"><span class="toc-item-num">1&nbsp;&nbsp;</span><i class="fa fa-tasks"></i> Python 
  </a></span></li><li><span><a href="#7번-해보기" data-toc-modified-id="7번-해보기-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>7번 해보기</a></span></li><li><span><a href="#-NumPy-
--" data-toc-modified-id="-NumPy-
---3"><span class="toc-item-num">3&nbsp;&nbsp;</span><i class="fa fa-tasks"></i> NumPy 
  </a></span></li><li><span><a href="#List-와-Array-차이" data-toc-modified-id="List-와-Array-차이-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>List 와 Array 차이</a></span></li><li><span><a href="#9번은-7번과-동일" data-toc-modified-id="9번은-7번과-동일-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>9번은 7번과 동일</a></span></li><li><span><a href="#-Pandas-
--" data-toc-modified-id="-Pandas-
---6"><span class="toc-item-num">6&nbsp;&nbsp;</span><i class="fa fa-tasks"></i> Pandas 
  </a></span></li><li><span><a href="#Reference" data-toc-modified-id="Reference-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Reference</a></span></li></ul></div>

In [1]:
import os
import sys
import warnings
warnings.filterwarnings(action='ignore')

---
<div class="alert alert-success" data-title="">
  <h2><i class="fa fa-tasks" aria-hidden="true"></i> Python 
  </h2>
</div>

![](https://i.pinimg.com/originals/a6/96/96/a696964ddaf552e14744451d256458d2.jpg)

**Q1.** You are given a list $x=[1,2,3,4,5,6]$. 

Print the third items in list x

In [4]:
𝑥=[1,2,3,4,5,6]

In [5]:
x[2] # 파이썬에서는 카운팅 0부터 된다.

3

**Q2.** Print the reversed order of list $x=[1,2,3,4,5,6]$

In [6]:
x[::-1]

[6, 5, 4, 3, 2, 1]

In [8]:
x[-1]

6

In [10]:
x[:-1]

[1, 2, 3, 4, 5]

In [11]:
x[-2:]

[5, 6]

**Q3.** Given a list iterate it and display numbers which are divisible by $5$ 

- List = [12, 15, 32, 42, 55, 75, 122, 132]
   

In [3]:
for i in [12, 15, 32, 42, 55, 75, 122, 132]:
    if i % 5 == 0 : 
        print(i)

15
55
75


**Q4.** Print the following pattern:
```
    1 
    1 2 
    1 2 3 
    1 2 3 4 
    1 2 3 4 5
```

In [21]:
for i in range(0,6):
    for j in range(1,i+1):
        print(j, end=' ')
    print("")


1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5 


**Q5.** Print the following pattern:

```
    5 4 3 2 1 
    4 3 2 1 
    3 2 1 
    2 1 
    1
    
    
```

In [30]:
for i in range(5,0,-1):
    for j in range(i,0,-1):
        print(j, end=' ')
    print("")

5 4 3 2 1 
4 3 2 1 
3 2 1 
2 1 
1 


**Q6.** The Fibonacci sequence is defined as below:
$$F_n = F_{n-1} + F_{n-2}$$

where $n$ denotes the $n^\text{th}$ item of the Fibonacci sequence. You are given the first three numbers of the Fibonacci sequence as F = [0, 1, 1]. Create a for loop to determine the next 20 numbers of the Fibonacci sequence. Print F with the final 23 numbers. 

_Hint: use F.append() to add a new Fibonacci value to the end of the list F._

In [35]:
F = [0,1, 1]

for n in range(3,23):
    
    f = F[n-1] +F[n-2]
    F.append(f)
print(F)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711]


## 7번 해보기

**Q7.** Given the list $x = [2.0,3.0,5.0,7.0,9.0]$, create a list $Y(x)$ for each float in x. Print the list $Y$.
$$Y(x) = \frac{(3.0x)^2}{(99x - x^3)} - \frac{1}{x}$$


In [121]:
def fun_y(t):

    bunja = ((3.0)*t)**2
    bunmo = (99*t - t**3)
    y  = (bunja / bunmo) - 1/t
    return y 

In [ ]:
fun_y()

In [40]:
x = [2.0, 3.0, 5.0, 7.0, 9.0] # 초기값 
y = [] # 빈 리스트 생성 

for t in x: 
    result = (((3.0)*t)**2) / (99*t - t**3) - (1/t)
#     result = fun_y(i)
    y.append(result)
print(y)


[-0.31052631578947365, -0.033333333333333326, 0.4081081081081081, 1.1171428571428572, 4.388888888888889]


---

<div class="alert alert-success" data-title="">
  <h2><i class="fa fa-tasks" aria-hidden="true"></i> NumPy 
  </h2>
</div>

![](https://datacamp-community-prod.s3.amazonaws.com/be48d587-e32a-4009-9c29-5b24f4a0edf3)

In [10]:
import numpy as np

**Q1.** Create a null vector of size 10 (★☆☆)

In [48]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [50]:
y =[]
for i in range(10):
    y.append(0.0)
print(y)

[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]


In [45]:
[0.0 for i in range(10)] #list_comprehension 

[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

In [53]:
type([2*i for i in range(10)])

list

In [54]:
np.array([2*i for i in range(10)])

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## List 와 Array 차이 

In [57]:
t = [1,2,3]
k = np.array(t)

In [59]:
print(f'리스트 t: {t}')
print(f'어레이 k: {k}')

리스트 t: [1, 2, 3]
어레이 k: [1 2 3]


In [60]:
# reshape  행렬 변형 
t.reshape(-1,1) # 행벡터를  열벡터로 

AttributeError: 'list' object has no attribute 'reshape'

In [61]:
k.reshape(-1,1)

array([[1],
       [2],
       [3]])

**Q2.** Reverse the below list(first element becomes last) (★☆☆):  

```python
x = [1,2,3,4,5]
```

In [65]:
x = [1,2,3,4,5]
x

[1, 2, 3, 4, 5]

In [66]:
type(x)

list

In [67]:
type(np.flip(x))

numpy.ndarray

**Q3.** Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)
(hint: np.linspace)

```python 
np.linspace(시작점, 끝점, 개수) 
```

In [74]:
np.linspace(0,1, 11,endpoint=False)

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091])

In [75]:
np.linspace(0,1, 11,endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

**Q4.** Create a random vector of size 10 and sort it (★★☆)

In [78]:
t = np.random.random(10)
t

array([0.88628238, 0.44346571, 0.80856968, 0.35782588, 0.25776748,
       0.08614263, 0.93410915, 0.84131193, 0.34032117, 0.67556334])

In [82]:
np.sort(t)

array([0.08614263, 0.25776748, 0.34032117, 0.35782588, 0.44346571,
       0.67556334, 0.80856968, 0.84131193, 0.88628238, 0.93410915])

**Q5.** Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [95]:
t = np.random.random((10,10))

In [96]:
t.max()

0.9794890102774118

In [97]:
t.min()

0.0041690871404814756

**Q6.** Create a 3x3x3 array with random values (★☆☆)

In [99]:
t = np.random.random((3,3,3))
t

array([[[0.52888146, 0.79946161, 0.0544054 ],
        [0.51947722, 0.79906688, 0.32137737],
        [0.65065625, 0.61800146, 0.65346221]],

       [[0.85632582, 0.73150696, 0.30165391],
        [0.37719661, 0.61771609, 0.05177263],
        [0.49204899, 0.97138846, 0.05567957]],

       [[0.76233748, 0.60078333, 0.99353704],
        [0.71025563, 0.25342596, 0.49791071],
        [0.43648342, 0.38580477, 0.77603766]]])

**Q7.** solve the equation $F=M \times a $  for a (hint: np.linalg.solve) 

```python 
M = np.array([[2,3],[-2,9]])
F = np.array([12.9,12.3])
```

In [100]:
M = np.array([[2,3],[-2,9]])
F = np.array([12.9,12.3])

In [101]:
np.linalg.solve(M,F)

array([3.3, 2.1])

**Q8.** dot product(matrix multiplication)

prodcut those two values t1, t2 
```python
t1 = np.array([[1,2],[2,3]])
t2 = np.array([[3,5],[4,6]])
```

In [102]:
t1 = np.array([[1,2],[2,3]])
t2 = np.array([[3,5],[4,6]])

In [103]:
t1 

array([[1, 2],
       [2, 3]])

In [104]:
t2

array([[3, 5],
       [4, 6]])

In [106]:
t1 * t2

array([[ 3, 10],
       [ 8, 18]])

In [107]:
t1 @ t2

array([[11, 17],
       [18, 28]])

## 9번은 7번과 동일

**Q9.** Consider the following four $x,y$ data points.

|$x$ |$y$| 
|--|--|
|0.0 | 1.1 |
|0.7 | 2.99| 
|1.7 | 5.69| 
|2.1 |6.77 |

where an equation of a line is defined as


$$y = mx + b$$

The matrix equation for fitting a line is defined as
\begin{equation}
\begin{bmatrix}
x_1 & 1.0 \\
x_2 & 1.0 \\
\vdots & \vdots \\
x_n & 1.0 \\
\end{bmatrix}\begin{bmatrix}
m  \\
b
\end{bmatrix}
= \begin{bmatrix}
y_1 \\
y_2 \\
\vdots \\
y_n \\
\end{bmatrix}
\end{equation} 

where the first data points are $x_1$ and $y_1$. The second data points are $x_2$ and $y_2$, and so forth. 


In [115]:
# 초기값 설정 
x = [0.0, 0.7, 1.7, 2.1 ]
t = [1, 1, 1, 1]
y = [1.1,2.99, 5.69, 6.77]

# vstack 행렬을 하나로 합쳐 줌
np.vstack((x,t))

array([[0. , 0.7, 1.7, 2.1],
       [1. , 1. , 1. , 1. ]])

In [116]:
# 전치 == transpose == T 
A = np.vstack((x,t)).T
A

array([[0. , 1. ],
       [0.7, 1. ],
       [1.7, 1. ],
       [2.1, 1. ]])

In [119]:
# least squared equaiton 
np.linalg.lstsq(A,y)

(array([2.7, 1.1]),
 array([1.19561731e-30]),
 2,
 array([3.2829449 , 1.00611768]))

---

<div class="alert alert-success" data-title="">
  <h2><i class="fa fa-tasks" aria-hidden="true"></i> Pandas 
  </h2>
</div>

![](https://media-exp1.licdn.com/dms/image/C5612AQEeBt4lps_6Hg/article-cover_image-shrink_720_1280/0?e=1601510400&v=beta&t=LfVlgjOt7mNBBTZ3W53fyBeQAn533PSVlEamNpiT2Zc)

In [122]:
import pandas as pd
import numpy as np 

In [124]:
pd.__version__

'1.0.3'

Note: remember to import numpy using:
```python
import numpy as np
```

Consider the following Python dictionary `data` and Python list `labels`:

``` python
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```
(This is just some meaningless data I made up with the theme of animals and trips to a vet.)

**Q4.** Create a DataFrame `df` from this dictionary `data` which has the index `labels`.

{} 딕셔러니 // [] 리스트 // () 튜플 

딕셔러리 = {key: value}

In [128]:
# 데이터 프레임을 만들자
pd.DataFrame()

df = pd.DataFrame(data={'animal': ['cat', 'cat', 'snake', 
                              'dog', 'dog', 'cat',
                              'snake', 'cat',
                              'dog', 'dog'],
                   # np.nan != 0 
                   'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
                   'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
                   'priority': ['yes', 'yes', 'no', 'yes', 'no', 
                                'no', 'no', 'yes', 'no', 'no']},
             index=['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'])

In [133]:
df.head(3)

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no

In [134]:
df.tail(3)

animal  age  visits priority
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

In [137]:
df.sample(2)

animal  age  visits priority
g  snake  4.5       1       no
c  snake  0.5       2       no

In [135]:
# 데이터프레임 정보 확인 
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   animal    10 non-null     object 
 1   age       8 non-null      float64
 2   visits    10 non-null     int64  
 3   priority  10 non-null     object 
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes


In [139]:
# 데이터 프레임에서도 인덱싱이 가능하다. 
df[:3]

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no

In [140]:
df

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

In [143]:
df['animal','age']

KeyError: ('animal', 'age')

In [144]:
df[['animal','age','visits']]

animal  age  visits
a    cat  2.5       1
b    cat  3.0       3
c  snake  0.5       2
d    dog  NaN       3
e    dog  5.0       2
f    cat  2.0       3
g  snake  4.5       1
h    cat  NaN       1
i    dog  7.0       2
j    dog  3.0       1

In [146]:
df[['animal','age']]

animal  age
a    cat  2.5
b    cat  3.0
c  snake  0.5
d    dog  NaN
e    dog  5.0
f    cat  2.0
g  snake  4.5
h    cat  NaN
i    dog  7.0
j    dog  3.0

In [151]:
df[['animal','age']].iloc[[3,4,8]]

animal  age
d    dog  NaN
e    dog  5.0
i    dog  7.0

In [154]:
df

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

In [156]:
df[(df['age'] > 2) & (df['visits'] >2)]

animal  age  visits priority
b    cat  3.0       3      yes

**Q9.** Select only the rows where the number of visits is greater than 3.

Empty DataFrame
Columns: [animal, age, visits, priority]
Index: []

**Q10.** Select the rows where the age is missing, i.e. it is `NaN`.

animal  age  visits priority
d    dog  NaN       3      yes
h    cat  NaN       1      yes

**Q11.** Select the rows where the animal is a cat *and* the age is less than 3.

animal  age  visits priority
a    cat  2.5       1      yes
f    cat  2.0       3       no

**Q12.** Select the rows the age is between 2 and 4 (inclusive).

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
f    cat  2.0       3       no
j    dog  3.0       1       no

**Q13.** Change the age in row 'f' to 1.5.

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

**Q14.** Calculate the sum of all visits in `df` (i.e. the total number of visits).

19

**Q15.** Calculate the mean age for each different animal in `df`.

animal
cat      2.333333
dog      5.000000
snake    2.500000
Name: age, dtype: float64

**Q16.** Append a new row 'k' to `df` with your choice of values for each column. Then delete that row to return the original DataFrame.

animal  age visits priority
a    cat  2.5      1      yes
b    cat    3      3      yes
c  snake  0.5      2       no
d    dog  NaN      3      yes
e    dog    5      2       no
f    cat  1.5      3       no
g  snake  4.5      1       no
h    cat  NaN      1      yes
i    dog    7      2       no
j    dog    3      1       no

**Q17.** Count the number of each type of animal in `df`.

dog      4
cat      4
snake    2
Name: animal, dtype: int64

**Q18.** Sort `df` first by the values in the 'age' in *decending* order, then by the value in the 'visit' column in *ascending* order (so row `i` should be first, and row `d` should be last).

animal  age visits priority
i    dog    7      2       no
e    dog    5      2       no
g  snake  4.5      1       no
j    dog    3      1       no
b    cat    3      3      yes
a    cat  2.5      1      yes
f    cat  1.5      3       no
c  snake  0.5      2       no
h    cat  NaN      1      yes
d    dog  NaN      3      yes

**Q19.** The 'priority' column contains the values 'yes' and 'no'. Replace this column with a column of boolean values: 'yes' should be `True` and 'no' should be `False`.

animal  age visits  priority
a    cat  2.5      1      True
b    cat    3      3      True
c  snake  0.5      2     False
d    dog  NaN      3      True
e    dog    5      2     False
f    cat  1.5      3     False
g  snake  4.5      1     False
h    cat  NaN      1      True
i    dog    7      2     False
j    dog    3      1     False

**Q20.** In the 'animal' column, change the 'snake' entries to 'python'.

animal  age visits  priority
a     cat  2.5      1      True
b     cat    3      3      True
c  python  0.5      2     False
d     dog  NaN      3      True
e     dog    5      2     False
f     cat  1.5      3     False
g  python  4.5      1     False
h     cat  NaN      1      True
i     dog    7      2     False
j     dog    3      1     False

## Reference

- https://rfriend.tistory.com/346